global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - api_url: "SLACK_WEBHOOK_URL" # Substitua pelo seu webhook do Slack
        channel: "#alertas-keepai"
        send_resolved: true
        title: "{{ .GroupLabels.alertname }}"
        text: "{{ range .Alerts }}*Alerta:* {{ .Annotations.summary }}\n*Descrição:* {{ .Annotations.description }}\n*Severidade:* {{ .Labels.severity }}\n{{ end }}"
