services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./server/templates:/app/templates
      - ./server/static:/app/static
      - ./server/config:/app/server/config
      - ./app.py:/app/app.py
    environment:
      - FLASK_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    stdin_open: true
    tty: true
