version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=server/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST=0.0.0.0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
